### ISSUE TITLE
Improve design of Calendar page

### ISSUE THREAD

**Issue by crowdpublishtv** [crowdpublishtv/crowdpublishtv#50]

**Comment by wiafe** [comment]
@crowdpublishtv How do you want it improved?

**Comment by crowdpublishtv** [comment]
Asking an engineer for design suggestions will not result in useful info. :/

I googled for Event Calendar Good Design images but didn't like what I saw very much. Here's something OK, except too many serifs
 http://www.designwagen.com/pictures/2011/11/Design-Calendar-of-Events-Fair-and-Festival.jpg

The events lists could use some work too.

**Comment by wiafe** [comment]
@crowdpublishtv Haha no worries, I'll take a look around.

**Comment by crowdpublishtv** [comment]
If you're interested, you can join us online for a tutorial discussion on Monday, 7:00pm EST. Check here at 6:45 for the google hangouts url http://www.meetup.com/railsgirlsdc/events/225927082/

**Comment by wiafe** [comment]
Sweet!

**Comment by crowdpublishtv** [comment]
Made some progress. Like all web sites, improving features & design is ongoing.
