### ISSUE TITLE
README not written in markdown

### ISSUE THREAD

**Issue by chrisdemars** [crowdpublishtv/crowdpublishtv#62]
I noticed that the README is not written in markdown and i would like to do that for you and submit a PR.

**Comment by crowdpublishtv** [comment]
That would be awesome, Chris. I'm encouraging people to get involved however they wish. Feel free to Hangout with us on Mon. evenings https://www.facebook.com/groups/crowdpublishtv/

**Comment by chrisdemars** [comment]
@crowdpublishtv I wish I could, but I don't have FB lol. I will start working on translating the README in to markdown this week.
